[git_status]
disabled=true


# configure directory
[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic #87A752"




[line_break]
disabled = true


# show the username. The username will only show in certain scenarios
[username]
style_user = "yellow bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "via [$hostname](bold red): "
trim_at = "-"
style = "bold dimmed white"
disabled = false


[cmd_duration]
disabled = true
